### ISSUE TITLE
make: wget: No such file or directory make: *** [static/lib/tinymce] Error 1

### ISSUE THREAD

**Issue by ypapax** [monsti/monsti#37]
<b>Tried to install monsti but got error:</b>

make: wget: No such file or directory
make: *** [static/lib/tinymce] Error 1

<b>Full output:</b>

$ make
GOPATH=/Users/user/Dropbox/golang/src/sana/monsti-monsti/go/ go get  pkg.monsti.org/monsti/core/monsti-daemon
wget -nv http://download.moxiecode.com/tinymce/tinymce_4.1.7.zip
make: wget: No such file or directory
make: *** [static/lib/tinymce] Error 1
user@host ~/Dropbox/golang/src/sana/monsti-monsti $

**Comment by chrneumann** [comment]
You need [wget](http://www.gnu.org/software/wget/). What environment are you using?

**Comment by ypapax** [comment]
Thank you. I installed `wget`. And the issue was resolved. I am using mac os.
