### ISSUE TITLE
deploy monsti from mac to ubuntu server

### ISSUE THREAD

**Issue by ypapax** [monsti/monsti#38]
I successfully run example `monsti` site `$GOPATH/monsti-try/monsti-monsti/example` on local `mac os` machine. 
Now how to deploy it to ubuntu server? Usually, I deploy go sites with the command ...
```GOOS=linux GOARCH=amd64 go build```
And then using `scp` command I transfer files to the server. If I can do the same with `monsti` where should I run this command?

Also, I tried to use [make dist](https://github.com/monsti/monsti/blob/master/doc/manual.adoc#deployment) command. But do not know exactly in what directory should I  run it and what will exactly this command do.

**Comment by chrneumann** [comment]
I added more information to the Build section in the manual: https://github.com/monsti/monsti/blob/develop/doc/manual.adoc#deployment

Does this help?

**Comment by ypapax** [comment]
Ok, how to create `make dist`? I tried this way:
user@host $GOPATH/sana/monsti-monsti/example $ make dist
make: *** No rule to make target `dist'.  Stop.

**Comment by chrneumann** [comment]
I updated the Build section once again. Hope that helps!

**Comment by ypapax** [comment]
Thank you. I run `make dist` in the main directory and go error:

user@host ~/GOPATH/sana/monsti-monsti $ sudo make dist
Password:
GOPATH=/Users/user/GOPATH/sana/monsti-monsti/go/ go get  pkg.monsti.org/monsti/core/monsti-daemon
mkdir -p /Users/user/GOPATH/sana/monsti-monsti/go//bin
cd utils/bcrypt && GOPATH=/Users/user/GOPATH/sana/monsti-monsti/go/ go get  -d . && GOPATH=/Users/user/GOPATH/sana/monsti-monsti/go/ go build  -o /Users/user/GOPATH/sana/monsti-monsti/go//bin/bcrypt .
ln -sf ../../go example/monsti-example-module/go
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C example/monsti-example-module
GOPATH=/Users/user/GOPATH/sana/monsti-monsti/example/monsti-example-module/go/ go get  -d
GOPATH=/Users/user/GOPATH/sana/monsti-monsti/example/monsti-example-module/go/ go build 
cp example/monsti-example-module/monsti-example-module /Users/user/GOPATH/sana/monsti-monsti/go//bin
rm -f templates/example
ln -sf ../example/monsti-example-module/templates templates/example
rm -Rf dist/monsti-0.10.0
mkdir -p dist/monsti-0.10.0/bin
cp go/bin/* dist/monsti-0.10.0/bin
mkdir -p dist/monsti-0.10.0/share
cp -RL locale static templates dist/monsti-0.10.0/share
mkdir -p dist/monsti-0.10.0/doc
cp CHANGES COPYING LICENSE README.md dist/monsti-0.10.0/doc
mkdir -p dist/monsti-0.10.0/etc
cp -R example/config/* dist/monsti-0.10.0/etc
mv dist/monsti-0.10.0/etc/sites/example dist/monsti-0.10.0/etc/sites/default
mkdir -p dist/monsti-0.10.0/run
mkdir -p dist/monsti-0.10.0/data
cp -R example/data/example dist/monsti-0.10.0/data/default
cp example/start.sh dist/monsti-0.10.0/
sed -i 's/\.\.\/go\///' dist/monsti-0.10.0/start.sh
sed: 1: "dist/monsti-0.10.0/star ...": extra characters at the end of d command
make: *** [dist] Error 1

**Comment by chrneumann** [comment]
Ok, there was an incompatibility with Mac's version of the sed command. Should be fixed now. I can't test it, I don't have access to a Mac. And it's only fixed in the development branch/version of Monsti. You can get it here: https://github.com/monsti/monsti/archive/develop.zip
