### ISSUE TITLE
Make not working for me :(

### ISSUE THREAD

**Issue by uriel-fanelli** [monsti/monsti#41]
Hi All

I downloaded monsti and i tried to compile it, but:

    mkdir -p /usr/home/loweel/mygo/src/monsti/go//src/pkg.monsti.org
    ln -sf ../../.. /usr/home/loweel/mygo/src/monsti/go//src/pkg.monsti.org/monsti
    GOPATH=/usr/home/loweel/mygo/src/monsti/go/ go get  pkg.monsti.org/monsti/core/monsti-daemon
    warning: code.google.com is shutting down; import path code.google.com/p/go.crypto/bcrypt will stop working
    package pkg.monsti.org/gettext: unrecognized import path "pkg.monsti.org/gettext"
    Makefile:95: recipe for target 'go/bin/monsti-daemon' failed

any suggestion?

**Comment by chrneumann** [comment]
Which version of Monsti are you trying to compile? Which Go version?

**Comment by uriel-fanelli** [comment]
I just did a git clone of the repo and I am using golang 1.5  .

**Comment by uriel-fanelli** [comment]
Update: seems the problem relies in 

pkg.monsti.org/gettext which cannot be "go get".

I also tried to do a manual go get of pkg.monsti.org/gettext , but it doesn't works.

**Comment by chrneumann** [comment]
Seems to be broken with Golang 1.5. Can you confirm that? Does it work with 1.3 or 1.4?

**Comment by uriel-fanelli** [comment]
I need to download and compile. I will do it asap, and let you know. Thanks for the answer. 

Btw, I see the url pkg.monsti.org/gettext os actually returning a http 302 to some github URL, and github is working. Why don't use github directly?

**Comment by chrneumann** [comment]
Because I don't want to be tied to one git hosting platform. Had been using Gitorious, then switched to Github. The import URLs didn't change.

**Comment by uriel-fanelli** [comment]
Hi, good news!

I compiled the 1.4.3 version of go, and I can confirm it compiles under go 1.4 .
Also, it works as expected. 

:)

I forgot some data last time, btw:

The platform is    freebsd/amd64
The compiler is   go 1.4.3 freebsd/amd64
Make: 
GNU Make 4.1
Built for amd64-portbld-freebsd10.1

just for reference.

Thanks for the help.

**Comment by chrneumann** [comment]
Fixed in development branch.
