### ISSUE TITLE
Can't Make with Go 1.5 on OS X

### ISSUE THREAD

**Issue by astorm** [monsti/monsti#42]
Hello!  I'm new to go and its various build tools, so apologies if this is something obvious.  I've cloned the master monsti project to my local computer (running OS X, 10.10.4).  When I attempt to `make` the project, I get the following error

    $ make
    GOPATH=/Users/alanstorm/Documents/github/monsti/monsti/go/ go get  pkg.monsti.org/monsti/core/monsti-daemon
    package pkg.monsti.org/gettext: unrecognized import path "pkg.monsti.org/gettext"
    make: *** [go/bin/monsti-daemon] Error 1

Same thing happened on the `develop` branch.

Running Go 1.5.1 (I think?)

    $ go version
    go version go1.5.1 darwin/amd64

Is there any known science to get this working?  Is there anything else I can do to help diagnose the problem and get things fixed?

**Comment by chrneumann** [comment]
Duplicate with #41 
Could not check it yet, because I had no access to Go 1.5.x. I'll have a look the next week.
